spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME:senior}:${DB_PASSWORD:junior}@localhost:27017/${DB_NAME:buy01}?authSource=admin

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}